name: CI

on:
  push:
  workflow_dispatch:

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    steps:
      - name: Run python
        run: |
          print("::group::System")
          import sys
          import os
          import time
          print(sys.version)
          print(os.environ['PATH'])
          print("::endgroup::")
        shell: python

  approval:
    needs: start
    environment: manual_approval
    name: Manual
    runs-on: ubuntu-latest
    steps:
      - name: Run python
        run: |
          echo "::group::Result"
          echo "Approved"
          echo "::endgroup::"
        shell: bash

  finish:
    needs: approval
    name: finish
    runs-on: ubuntu-latest
    concurrency:
      group: concurrency-ci
      cancel-in-progress: true
    steps:
      - name: Run python
        run: |
          import sys
          import os
          import time

          print(sys.version)
          print(os.environ['PATH'])
          time.sleep(3)
        shell: python