name: CI

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types: [requested]
    branches:
      - 'releases/**'

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    steps:
      - name: Run python
        run: |
          import sys
          import os
          import time

          print(sys.version)
          print(os.environ['PATH'])
          time.sleep(3)
        shell: python

  approval:
    concurrency:
      group: concurrency-ci
    needs: start
    environment: manual_approval
    name: Manual
    runs-on: ubuntu-latest
    steps:
      - name: Run python
        run: echo "Foi"
        shell: bash

  finish:
    needs: approval
    name: finish
    runs-on: ubuntu-latest
    steps:
      - name: Run python
        run: |
          import sys
          import os
          import time

          print(sys.version)
          print(os.environ['PATH'])
          time.sleep(30)
        shell: python