name: '2. workflow dispatch with parameters'

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Type a word'
        required: true
        type: string

jobs:
  dispatch:
    name: My job with dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: echo "Workflow dispatch receive ${{ inputs.text }}"