name: '2. workflow dispatch with parameters'

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'runs-on name'
        required: true
        type: string

jobs:
  dispatch:
    name: My job with dispatch
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Print
        run: echo "Success"
