name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run python
        run: echo "Deploy"
        shell: bash